apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: mohri1219/skaffold-example-frontend
    context: php-redis
  - image: mohri1219/skaffold-example-redis-slave
    context: redis-slave
  local:
    push: false
test:
  - image: mohri1219/skaffold-example-frontend
    structureTests:
      - ./structure-test/frontend.yaml
deploy:
  kubectl:
    manifests:
    - frontend-*.yaml
    - redis-master-*.yaml
    - redis-slave-*.yaml
    - guestbook-ingress.yaml

profiles:
- name: prd
  build:
    local:
      push: true
  deploy:
    kubectl:
      manifests:
      - frontend-*.yaml
      - redis-master-*.yaml
      - redis-slave-*.yaml
