apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: mohri1219/skaffold-example-frontend
    context: php-redis
  - image: mohri1219/skaffold-example-redis-slave
    context: redis-slave
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - frontend-deployment.yaml
    - frontend-service.yaml
    - redis-master-deployment.yaml
    - redis-master-service.yaml
    - redis-slave-deployment.yaml
    - redis-slave-service.yaml
